# Maven



trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
public class AddTwoIntegers {
    public static void main(String[] args) {
        
        int first = 10;
        int second = 20;
        int sum = first + second;
        System.out.println("The sum is: " + sum);
    }
}'
